# Generated by Django 6.0.3 on 2026-03-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthname', models.CharField()),
                ('challenge', models.CharField()),
            ],
            options={
                'verbose_name': 'MonthlyChallenge',
                'verbose_name_plural': 'MonthlyChallenges',
            },
        ),
    ]
