# Generated by Django 6.0.3 on 2026-03-25 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0006_watchlist_platformtostream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='platformtostream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platformstreams', to='watchlist_app.streamplatform'),
        ),
    ]
